exports.messaging = {
  //AUTH SERVICE QUEUES
  AUTH_SERVICE_UPDATE_DRIVER: "AUTH_SERVICE_UPDATE_DRIVER",
  AUTH_SERVICE_FETCH_DRIVER: "AUTH_SERVICE_FETCH_DRIVER",

  //RIDE SERVICE QUEUES
  RIDE_SERVICE_APPROVE_DRIVER: "RIDE_SERVICE_APPROVE_DRIVER",
  
  //NOTIFICATION SERVICE
  NOTIFICATION_MAIL_TO_NEW_INSPECTOR: "NOTIFICATION_MAIL_TO_NEW_INSPECTOR",

  USER_OTP_SMS: "USER_OTP_SMS",
  OTP_EMAIL_VERIFICATION: "OTP_EMAIL_VERIFICATION",


};

exports.OrderStatus = {
  PENDING: "pending",
  CANCELLED: "cancelled",
  COMPLETED: "completed",
  ACCEPTED: "accepted",
};

exports.TripMatchStatus = {
  PENDING: "pending",
  REJECTED: "rejected",
  ACCEPTED: "accepted",
};



